# تنظیمات کلی
SYMBOLS = ["BTC-USDT", "ETH-USDT", "SOL-USDT"]
TIMEFRAME = "15min"
CANDLES_LIMIT = 500

# مدل‌ها
LSTM_LOOKBACK = 50
XGBOOST_N_ESTIMATORS = 100

# مدیریت ریسک
RISK_REWARD_RATIO = 3.0  # نسبت سود به ضرر: 3:1
ATR_MULTIPLIER_SL = 1.0   # حد ضرر = 1.0 × ATR
INITIAL_CAPITAL = 10000

# تلگرام
SEND_TELEGRAM = True
